name: Pipeline

on:
  pull_request:
    types: [opened]
    branches:
      - dev
#  push:
  workflow_dispatch:
    inputs:
      ci_build_lightweight:
        description: "Is it a lightweight build? One of [true, false, auto]."
        required: true
        default: "auto"
      git_source_branch:
        description: "GIT source branch name. For example [dev, master...]."
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OWNER: StanleyProjects
      GITHUB_REPO: ScheduleView
      telegram_bot_id: ${{secrets.TELEGRAM_BOT_ID}}
      telegram_bot_token: ${{secrets.TELEGRAM_BOT_TOKEN}}
      telegram_chat_id: ${{secrets.TELEGRAM_CHAT_ID_COMMON}}
      github_pat: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      RESOURCES_PATH: buildSrc/src/main/resources
    steps:
      - name: test env write
        id: env_write
        if: github.event_name == 'pull_request'
        run: |
          echo "PR_NUMBER=$(jq -r .pull_request.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
      - name: test env read
        id: env_read
        if: github.event_name == 'pull_request'
        run: |
          echo "PR_NUMBER [${{env.PR_NUMBER}}]"
          echo "PR_NUMBER [$PR_NUMBER]"
      - if: github.event_name == 'pull_request'
        run: |
          echo ::set-env name=PR_NUMBER::$(jq -r .pull_request.number $GITHUB_EVENT_PATH)
          echo ::set-env name=PR_SOURCE_BRANCH::$(jq -r .pull_request.base.ref $GITHUB_EVENT_PATH)
          echo ::set-env name=GIT_SOURCE_BRANCH::$(jq -r .pull_request.head.ref $GITHUB_EVENT_PATH)
          echo ::set-env name=GIT_COMMIT_SHA::$(jq -r .pull_request.head.sha $GITHUB_EVENT_PATH)
          echo ::set-env name=CI_BUILD_LIGHTWEIGHT::auto
      - if: github.event_name == 'workflow_dispatch'
        run: |
          echo ::set-env name=CI_BUILD_LIGHTWEIGHT::${{github.event.inputs.ci_build_lightweight}}
          echo ::set-env name=GIT_SOURCE_BRANCH::${{github.event.inputs.git_source_branch}}
          echo ::set-env name=GIT_COMMIT_SHA::$(jq -r .after $GITHUB_EVENT_PATH)
      - run: git clone -q --depth=1 --branch=$GIT_SOURCE_BRANCH https://github.com/$GITHUB_OWNER/$GITHUB_REPO.git repository
      - if: github.event_name == 'workflow_dispatch'
        run: |
          echo ::set-env name=GIT_COMMIT_SHA::$(git --git-dir=repository/.git rev-parse $GIT_SOURCE_BRANCH)
      - working-directory: repository
        run: /bin/bash $RESOURCES_PATH/bash/workflow/main.sh