name: Pipeline

on:
  pull_request:
    types: [opened]
    branches:
      - dev
#  push:
  workflow_dispatch:
    inputs:
      ci_build_lightweight:
        description: "Is it a lightweight build? One of [true, false, auto]."
        required: true
        default: "auto"
      git_source_branch:
        description: "GIT source branch name. For example [dev, master...]."
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      RESOURCES_PATH: buildSrc/src/main/resources
    steps:
      - working-directory: repository
        run: /bin/bash $RESOURCES_PATH/bash/workflow/main.sh