name: Pipeline

on:
  pull_request:
    types: [opened]
    branches:
      - dev
#  push:
  workflow_dispatch:
    inputs:
      ci_build_lightweight:
        description: "Is it a lightweight build? One of [true, false, auto]."
        required: true
        default: "auto"
      git_source_branch:
        description: "GIT source branch name. For example [dev, master...]."
        required: true
        default: "dev"
